### ISSUE TITLE
play store content

### ISSUE THREAD

**Issue by synapticleft** [quendera/TheSpinnerGame#70]
#1 remove 'strategy biasing' images from play store (all the screenshots that are without text).

**Comment by quendera** [comment]
fixed

**Comment by synapticleft** [comment]
for some reason when i am on the play store on my laptop browser i see 3 copies of the images, and the last 2 sets still have the original screenshots. In the phone, one extra screenshot is still there. i tried refreshing as well as a different browser.
